version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 428694752194.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - docker build -t zainazam .
      - docker tag zainazam:latest 428694752194.dkr.ecr.us-west-2.amazonaws.com/zainazam:latest
  post_build:
    commands:
      - docker push 428694752194.dkr.ecr.us-west-2.amazonaws.com/zainazam:latest
      - printf '[{"name":"myData","imageUri":"%s"}]' 428694752194.dkr.ecr.us-west-2.amazonaws.com/zainazam:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
